name: Push to Amazon ECR

on:
  push:
    branches: [ 'master' ]

jobs:
  build:

    runs-on: ubuntu-latest

    steps:
    - uses: actions/checkout@v2
    - run: docker build -f Dockerfile.prod -t ${{ secrets.AWS_ECR_TAG }}:latest .
    - name: Push to ECR    
      id: ecr
      uses: jwalton/gh-ecr-push@v1
      with:
        access-key-id: ${{ secrets.AWS_ACCESS_KEY_ID }}
        secret-access-key: ${{ secrets.AWS_SECRET_ACCESS_KEY }}
        region: ${{ secrets.AWS_REGION }}
        image: ${{ secrets.AWS_ECR_TAG }}:latest
  redeploy:
      name: Continuous Deployment
      runs-on: ubuntu-18.04
      
      needs: [build]
      steps:
        - name: Deploy docker container webhook
          uses: joelwmale/webhook-action@master
          env:
            WEBHOOK_URL: ${{ secrets.WEBHOOK_PROD_DEPLOY_URL  }}
            data: "{ 'pass': '${{ secrets.WEBHOOK_PROD_DEPLOY_PASS }}'}"